MATCH (callerSpec)<-[:CORRESPONDING_SPECIFICATION]-(caller:A_FUNCTION_BODY_DECLARATION|A_FUNCTION_BODY_STUB|A_PROCEDURE_BODY_DECLARATION|A_PROCEDURE_BODY_STUB|A_PROTECTED_BODY_DECLARATION|A_PROTECTED_BODY_STUB|A_TASK_BODY_DECLARATION|A_TASK_BODY_STUB|AN_ENTRY_BODY_DECLARATION|AN_EXPRESSION_FUNCTION_DECLARATION)<-[:IS_ENCLOSED_IN*]-(subProgCall:A_PROCEDURE_CALL_STATEMENT|A_FUNCTION_CALL)<-[:IS_ENCLOSED_IN]-(id:AN_IDENTIFIER)-[:CORRESPONDING_NAME_DEFINITION]->(:A_DEFINING_IDENTIFIER)-[:IS_ENCLOSED_IN]->()-[:CORRESPONDING_SPECIFICATION]->(subProg)
MERGE (callerSpec)-[r:CALLING]->(subProg)
ON CREATE
  SET r.nbCall = 1
ON MATCH
  SET r.nbCall = r.nbCall + 1
