package Export_Utils is
    type Props_Kind is (PK_Boolean, PK_Integer);

    type Relation_Kinds is
       (CORRESPONDING_ACTUAL_PARAMETER, CORRESPONDING_ASSIGNATION, CORRESPONDING_FIRST_SUBTYPE,
        CORRESPONDING_FORMAL_NAME, CORRESPONDING_INSTANTIATION, CORRESPONDING_NAME_DEFINITION,
        CORRESPONDING_PARAMETER_SPECIFICATION, CORRESPONDING_ROOT_TYPE, CORRESPONDING_SPECIFICATION,
        CORRESPONDING_TYPE_DECLARATION_VIEW, IS_ENCLOSED_IN, IS_OF_TYPE);

end Export_Utils;
